# Generated by Django 6.0.1 on 2026-02-18 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ishemalinkuseraccountmodel",
            name="the_phone_number_starting_with_plus_250",
        ),
        migrations.RemoveField(
            model_name="ishemalinkuseraccountmodel",
            name="the_sixteen_digit_rwandan_national_id_number_for_kyc",
        ),
        migrations.AddField(
            model_name="ishemalinkuseraccountmodel",
            name="is_identity_verified_by_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ishemalinkuseraccountmodel",
            name="the_16_digit_rwandan_nid_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ishemalinkuseraccountmodel",
            name="this_user_is_either_an_agent_or_a_customer_type",
            field=models.CharField(default="DRIVER", max_length=20),
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "shipment_type",
                    models.CharField(
                        choices=[
                            ("DOMESTIC", "Domestic"),
                            ("INTERNATIONAL", "International"),
                        ],
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tariff_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("PAID", "Paid/Processing"),
                            ("DISPATCHED", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Payment Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver_assigned",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "this_user_is_either_an_agent_or_a_customer_type": "DRIVER"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("provider", models.CharField(default="MTN_MOMO", max_length=50)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="core.shipment",
                    ),
                ),
            ],
        ),
    ]
