# Generated by Django 6.0.1 on 2026-02-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ishemalinkuseraccountmodel",
            old_name="the_sixteen_digit_rwandan_national_id_number_for_kyc",
            new_name="the_16_digit_rwandan_nid_number",
        ),
        migrations.RemoveField(
            model_name="ishemalinkuseraccountmodel",
            name="the_phone_number_starting_with_plus_250",
        ),
        migrations.AddField(
            model_name="ishemalinkuseraccountmodel",
            name="is_identity_verified_by_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ishemalinkuseraccountmodel",
            name="phone_number_for_otp",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="ishemalinkuseraccountmodel",
            name="this_user_is_either_an_agent_or_a_customer_type",
            field=models.CharField(default="CUSTOMER", max_length=20),
        ),
    ]
