# Generated by Django 6.0.1 on 2026-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackageShipmentTrackingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number_generated_by_system",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "current_package_status_right_now",
                    models.CharField(default="PENDING", max_length=50),
                ),
                ("receiver_phone_number_for_sms", models.CharField(max_length=13)),
                (
                    "history_of_where_the_package_has_been",
                    models.TextField(default="Package Created"),
                ),
            ],
        ),
    ]
