# Generated by Django 6.0.2 on 2026-02-21 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domestic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="driver_assigned",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "DRIVER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domestic_driven_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domestic_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="IshemaLinkUserAccountModel",
        ),
    ]
