# Generated by Django 6.0.1 on 2026-02-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=50, unique=True)),
                ("sender_name", models.CharField(max_length=100)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
